### ISSUE TITLE
No module named 'case'

### ISSUE THREAD

**Issue by kpbleung** [basler/pypylon#194]
Hi, I used pip to install pylon and it appeared the install was successful.  However, when I tried to import it, i get the following error.

import pylon
Traceback (most recent call last):

  File "<ipython-input-1-d1fefb2fb6dd>", line 1, in <module>
    import pylon

  File "/anaconda/lib/python3.6/site-packages/Pylon-0.4.4-py3.6.egg/pylon/__init__.py", line 17, in <module>
    from case import Case, Bus, Branch

ModuleNotFoundError: No module named 'case'

**Comment by kpbleung** [comment]
Sorry, I noticed right after I posted my question.  My bad!
