### ISSUE TITLE
Import Error after installing wheel but not when building from repo

### ISSUE THREAD

**Issue by mattcarp12** [basler/pypylon#238]
I am trying to install pypylon in a docker container on an ARM device. Here is my docker file:

```Dockerfile
FROM ubuntu

ARG PYLON=pylon_5.2.0.13457-deb0_arm64.deb
ARG PYPYLON=https://github.com/basler/pypylon/releases/download/1.5.4/pypylon-1.5.4-cp38-cp38-linux_aarch64.whl
COPY ./deps/$PYLON /tmp/
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update &&  apt-get install -y locales 
RUN    sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
RUN    dpkg-reconfigure --frontend=noninteractive locales 
RUN update-locale LANG=en_US.UTF-8 && export LANG='en_US.UTF-8' 
RUN apt-get install -f /tmp/$PYLON 
RUN rm /tmp/$PYLON 
RUN apt-get install -y build-essential python3-dev libxslt-dev gcc gfortran libopenblas-dev liblapack-dev libopenblas-base libatlas3-base 
RUN apt-get install -y python3-scipy python3-opencv python3-skimage python3-pip swig git
RUN apt-get autoremove -y 
RUN pip3 install --upgrade setuptools pip
RUN pip3 install --no-cache-dir opcua redis wheel flask imutils rq pyyaml influxdb 
RUN pip3 install $PYPYLON
```

When I build this image everything installs fine but when I try to run `from pypylon import pylon` from the terminal or script I get the following exception:
```python
>>> from pypylon import pylon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/pypylon/pylon.py", line 40, in <module>
    from . import _pylon
```

However when I replace the last line of the dockerfile with the following,
```Dockerfile
RUN git clone https://github.com/basler/pypylon.git && cd pypylon && pip install .
```
then everything works fine.

I have no problem using the second way, just wanted to understand what is causing this error.

**Comment by Merwanski** [comment]
Hey @mattcarp12 

I had a similar issue with python3 but after running 
$ git clone https://github.com/basler/pypylon.git && cd pypylon && pip install .
the problem was solved 

I don't know exactly what went wrong during the first installation 

Merwan
