### ISSUE TITLE
_genicam.TimeoutException: Grab timed out. : TimeoutException thrown (file 'instantcameraimpl.h', line 1064)

### ISSUE THREAD

**Issue by ToKraTheSecond** [basler/pypylon#382]
I am able to take single shot and continuous shot via pylon viewer, but not via pypylon examples. For example [gige_action_command.py](https://github.com/basler/pypylon/blob/master/samples/gige_action_command.py) returns:

```
using a2A1920-51gcPRO @ 192.168.111.193
ActionDeviceKey 0x0
ActionGroupKey 0x0
ActionGroupMask 0x0
TriggerSource Line1
TriggerMode Off
AcquisitionMode SingleFrame


ActionDeviceKey 0x4711
ActionGroupKey 0x112233
ActionGroupMask 0xffffffff
TriggerSource Line1
TriggerMode Off
AcquisitionMode Continuous


issuing no-wait action command
Traceback (most recent call last):
  File "test.py", line 108, in <module>
    with cam.RetrieveResult(1000, pylon.TimeoutHandling_ThrowException):
  File "c:\tools\Anaconda3\envs\basler-cams\lib\site-packages\pypylon\pylon.py", line 3458, in RetrieveResult
    return _pylon.InstantCamera_RetrieveResult(self, *args)
_genicam.TimeoutException: Grab timed out. : TimeoutException thrown (file 'instantcameraimpl.h', line 1064)
```

* cam: a2A1920-51gcPRO GigE
* network settings:
    * cam <-PoE-> PoE switch <-GigEth-> ntb
    * all IPs are static
    * switch IP: 192.168.111.192
    * cam IP: 192.168.111.193
    * ntb eth adapter: 192.168.111.194
* ntb OS: WIN 10 Pro
* pypylon version: 1.7.2
* python version 3.8.10
* pylon viewer version: pylon 6 Camera Software Suite 6.2.0.21487
* PoE Switch: Ubiquiti US-8-60W

Can anybody pls pinpoint me how to solve / debug this issue?

**Comment by ToKraTheSecond** [comment]
Exported cam node settings: [node_map_a2A1920-51gcPRO.txt](https://github.com/basler/pypylon/files/6725230/node_map_a2A1920-51gcPRO.txt)

**Comment by ToKraTheSecond** [comment]
I double checked all settings and for some reason _pylon GigE Vision Driver_ was not turned on in ethernet adapter settings. As mentioned in docs _Network Configuration (GigE Cameras)_ [basler docs link](https://docs.baslerweb.com/network-configuration-(gige-cameras)). But I set it on few days ago :/. Weird :O :)

It works now : ))
