### ISSUE TITLE
Cannot import pypylon modules on jetson xavier

### ISSUE THREAD

**Issue by Zillibub** [basler/pypylon#522]
Hello, 

Pylon version: 7.1.0

I build module with the following command: `pip install git+https://github.com/basler/pypylon.git` in venv

But when I try to import module, it returns the following error: 
```
from pypylon import pylon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/inference-env/lib/python3.8/site-packages/pypylon/pylon.py", line 40, in <module>
    from . import _pylon
ImportError: libpylonbase.so.7.1: cannot open shared object file: No such file or directory
```

**Comment by thiesmoeller** [comment]
As a quick workaround install latest  pylon 6.x version.
7.1 support hasn't been integrated yet

**Comment by Zillibub** [comment]
Worked like a charm, thanks!

**Comment by tonynajjar** [comment]
Any update if pypylon supports Pylon versions >7.*?
