### ISSUE TITLE
capture error

### ISSUE THREAD

**Issue by centurions** [basler/pypylon#552]
Hello
I get this error after running opencv.py example but it works normally in pylon viewer .

Traceback (most recent call last):
  File "opencv.py", line 21, in <module>
    grabResult = camera.RetrieveResult(5000, pylon.TimeoutHandling_ThrowException)
  File "C:\secsys\snake\lib\site-packages\pypylon\pylon.py", line 3495, in RetrieveResult
    return _pylon.InstantCamera_RetrieveResult(self, *args)
_genicam.TimeoutException: Grab timed out. Possible reasons are: The image transport from the camera device is not working properly, e.g., all GigE network packets for streaming are dropped; The camera uses explicit triggering (see TriggerSelector for more information) and has not been triggered; Single frame acquisition mode is used and one frame has already been acquired; The acquisition has not been started or has been stopped. : TimeoutException thrown (file 'instantcameraimpl.h', line 1037)

**Comment by SMA2016a** [comment]
if you use pylon viewer, grab image successfully, then run the Grab.py will work?
