### ISSUE TITLE
Can't get grab result or recover from timeout

### ISSUE THREAD

**Issue by fpagliughi** [basler/pypylon#77]
On Linux Ubuntu 16.04, using a Dart daA1280-54um, when I have a capture timeout, I get an exception, seemingly from the C++ library, whether I ask for a timeout exception or not. And then nothing I do lets me recover from the timeout.

For example:
```
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pypylon import pylon
>>> cam = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice())
>>> cam.Open()
>>> cam.GetDeviceInfo().GetModelName()
'daA1280-54um'
>>> cam.StartGrabbing()
>>> res = cam.RetrieveResult(1.0, pylon.TimeoutHandling_Return)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pypylon/pylon.py", line 2951, in RetrieveResult
    return _pylon.InstantCamera_RetrieveResult(self, *args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'InstantCamera_RetrieveResult'.
  Possible C/C++ prototypes are:
    Pylon::CInstantCamera::RetrieveResult(unsigned int,Pylon::CGrabResultPtr &,Pylon::ETimeoutHandling)
    Pylon::CInstantCamera::RetrieveResult(unsigned int,Pylon::CGrabResultPtr &)

>>> res = cam.RetrieveResult(5000.0, pylon.TimeoutHandling_Return)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pypylon/pylon.py", line 2951, in RetrieveResult
    return _pylon.InstantCamera_RetrieveResult(self, *args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'InstantCamera_RetrieveResult'.
  Possible C/C++ prototypes are:
    Pylon::CInstantCamera::RetrieveResult(unsigned int,Pylon::CGrabResultPtr &,Pylon::ETimeoutHandling)
    Pylon::CInstantCamera::RetrieveResult(unsigned int,Pylon::CGrabResultPtr &)
```

In the first RetrieveResult, I specify a timeout. of 1.0 Clearly this is too short, and should result in a timeout error. But even though I requested a `TimeoutHandling_Return`, it throws an exception. And the exception seems to be a problem with the Python wrapper API - not a timeout exception.

Then, no matter what I do, I can't seem to clear the result - even if I leave grabbing mode and start again.

**Comment by fpagliughi** [comment]
Oops!  My bad. I used a floating point number for the timeout. It should be an integer.
