### ISSUE TITLE
Editing white balance & color transformation parameters - Node not existing (file 'genicam_wrap.cpp', line 16138) error

### ISSUE THREAD

**Issue by frankbrewer** [basler/pypylon#781]
### Describe what you want to implement and what the issue & the steps to reproduce it are:

Hi,

I am trying to change white balance (https://docs.baslerweb.com/balance-white) and color transformation parameters (https://docs.baslerweb.com/color-transformation#how-it-works) of my Basler ace L camera using pypylon. But I am getting the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/frankbrewer/anaconda3/envs/pylon/lib/python3.12/site-packages/pypylon/pylon.py", line 4400, in __getattr__
    return self.GetNodeMap().GetNode(attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/frankbrewer/anaconda3/envs/pylon/lib/python3.12/site-packages/pypylon/genicam.py", line 1360, in GetNode
    return _genicam.INodeMap_GetNode(self, Name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_genicam.LogicalErrorException: Node not existing (file 'genicam_wrap.cpp', line 16138)
```

Here is what I am doing: (throws error directly after trying to set red channel intensity)

```
from pypylon import pylon

tlf = pylon.TlFactory.GetInstance()
camera = pylon.InstantCamera(tlf.CreateFirstDevice())

camera.Open()

# enable software trigger
camera.TriggerSelector.Value = "FrameStart"
camera.TriggerSource.Value = "Software"
camera.TriggerMode.Value = "On"

# Set the red intensity
camera.BalanceRatioSelector.Value = "Red"
camera.BalanceRatio.Value = 4.852
# Set the green intensity
camera.BalanceRatioSelector.Value = "Green"
camera.BalanceRatio.Value = 4.371
# Set the blue intensity
camera.BalanceRatioSelector.Value = "Blue"
camera.BalanceRatio.Value = 5.799


# Select position Gain00 in the matrix
camera.ColorTransformationValueSelector.Value = "Gain00"
# Enter a floating point value for the selected position
camera.ColorTransformationValue.Value = 0.926
# Select position Gain01 in the matrix
camera.ColorTransformationValueSelector.Value = "Gain01"
# Enter a floating point value for the selected position
camera.ColorTransformationValue.Value = -0.028

camera.ColorTransformationValueSelector.Value = "Gain02"
# Enter a floating point value for the selected position
camera.ColorTransformationValue.Value = 0.044

camera.ColorTransformationValueSelector.Value = "Gain10"
# Enter a floating point value for the selected position
camera.ColorTransformationValue.Value = 0.003
# Select position Gain01 in the matrix
camera.ColorTransformationValueSelector.Value = "Gain11"
# Enter a floating point value for the selected position
camera.ColorTransformationValue.Value = 0.866

camera.ColorTransformationValueSelector.Value = "Gain12"
# Enter a floating point value for the selected position
camera.ColorTransformationValue.Value = 0.086

camera.ColorTransformationValueSelector.Value = "Gain20"
# Enter a floating point value for the selected position
camera.ColorTransformationValue.Value = -0.022
# Select position Gain01 in the matrix
camera.ColorTransformationValueSelector.Value = "Gain21"
# Enter a floating point value for the selected position
camera.ColorTransformationValue.Value = 0.089

camera.ColorTransformationValueSelector.Value = "Gain22"
# Enter a floating point value for the selected position
camera.ColorTransformationValue.Value = 0.848

```

Could you help me with this?

### Is your camera operational in Basler pylon viewer on your platform

Yes

### Hardware setup & camera model(s) used

PC X86_64

### Runtime information:

```shell
python: 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:50:58) [GCC 12.3.0]
platform: linux/x86_64/6.8.0-40-generic
pypylon: 4.0.0 / 8.0.0.10
```

**Comment by frankbrewer** [comment]
I noticed that BalanceRatioRaw.Value should be used instead of BalanceRatio.Value, but I still do not have an idea about ColorTransformationValueSelector.Value
