### ISSUE TITLE
Installing pypylon

### ISSUE THREAD

**Issue by Nemarott** [basler/pypylon#795]
### Describe what you want to implement and what the issue & the steps to reproduce it are:

Hello I tried installing pypylon on Windows via the cmd with the command py -m pip install git+https://github.com/basler/pypylon but I got the message:
Collecting git+https://github.com/basler/pypylon
  Cloning https://github.com/basler/pypylon to c:\users\adria\appdata\local\temp\pip-req-build-79fhp8le
  Running command git clone --filter=blob:none --quiet https://github.com/basler/pypylon 'C:\Users\adria\AppData\Local\Temp\pip-req-build-79fhp8le'
  Resolved https://github.com/basler/pypylon to commit 1d152526905b8e34b41e67ec1e99b3d9ee5b3d2d
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "C:\Users\adria\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\adria\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\adria\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\adria\AppData\Local\Temp\pip-build-env-fddwkjai\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\adria\AppData\Local\Temp\pip-build-env-fddwkjai\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\adria\AppData\Local\Temp\pip-build-env-fddwkjai\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 1093, in <module>
        File "<string>", line 370, in make
        File "<string>", line 542, in __init__
      OSError: PYLON_DEV_DIR is not set
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: C:\Users\adria\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Do I have to install pypylon in an other way oris there something else wrong?
My python version is 3.12.7 my pip version is 24.2 and my git version is 2.47.0.windows.2. I also tried to install it with python 3.13 but got the same error.

### Is your camera operational in Basler pylon viewer on your platform

Yes

### Hardware setup used

Windows

### Camera(s) used

Basler acA3088-57um

### Runtime information:

```shell
None
```

**Comment by HighImp** [comment]
Hi, if you dont want to build pypylon, the way to get it from pypi is only using the package name: 
pip install pypylon
Sorry that i not wrote you that in the samples repository, 
i stopped after you wrote that you used python 3.13.
